### ISSUE TITLE
percent encode `[` and `]` in URLs

### ISSUE THREAD

**Issue by line-o** [BetaMasaheft/Manuscripts#1858]
For some reason xmllint, relax-ng or the combination of both tools flag URLs that contain `[` and `]` as invalid.

As a workaround they can be percent encoded in order for them to be valid against the current schema.
- `[` => `%5B`
- `]` => `%5D`

**Example:**

https://github.com/BetaMasaheft/Manuscripts/blob/bcdfa66f5f81ec4b8bca9c7c93888641ef081efb/Frankfurt/FSUfferueppII1.xml#L162

```
http://dfg-viewer.de/show/?set[mets]=...
```
changes to

```
http://dfg-viewer.de/show/?set%5Bmets%5D=...
```

**Comment by line-o** [comment]
What we don't know yet is what repercussions this change in the data might have later on.
Will the expansion work? What will the expanded file look like?
Does this affect the display in the web application?

**Comment by line-o** [comment]
@eu-genia With this change applied all the Frankfurt files do validate

**Comment by eu-genia** [comment]
@thea-m @DenisNosnitsin1970 - for all to consider when encoding URLs, we should html-encode square brackets

**Comment by eu-genia** [comment]
we probably should add this to guidelines somewhere not to forget

**Comment by duncdrum** [comment]
I have tried to find out if this is a bug or not and frankly given up. There seems to be general agreement with respect to interpreting the relevant standards that encoding `[` and `]` is a good idea as these are risky characters. 

But using `[]` brackets inside URLs for reasons other then signifying a ipv6 literal, splits reviewers in half with respect to being valid or not. Since the fix is already committed I suggest we close this issue without creating a follow up ticket.
